export const BODY_PARTS_LABELS = {
    skin: "Skin",
    skeleton: "Skeleton",
    eyes: "Eyes",
    brain: "Brain",
    thyroid: "Thyroid",
    thymus: "Thymus",
    heart: "Heart",
    lungs: "Lungs",
    liver: "Liver",
    stomach: "Stomach",
    pancreas: "Pancreas",
    spleen: "Spleen",
    kidneys: "Kidneys",
    "small-intestine": "Small Intestine",
    "large-intestine": "Large Intestine",
    appendix: "Appendix",
    "nervous-system": "Nervous System",
    "respiratory-system": "Respiratory System",
    "circulatory-system": "Circulatory System",
    "digestive-system": "Digestive System",
    "excretory-system": "Excretory System",
    "immune-system": "Immune System",
    "male-endocrine-system": "Male Endocrine System",
    "female-endocrine-system": "Female Endocrine System",
    "male-reproductive-system": "Male Reproductive System",
    "female-reproductive-system": "Female Reproductive System",
} as const;
export type BodyPart = keyof typeof BODY_PARTS_LABELS;
